/**
 * Todo interface - represents a todo item
 * This is our main data model that will be used throughout the application
 */
export interface ITodo {
  _id?: string; // MongoDB document ID (optional because it's not present when creating a new todo)
  title: string; // The title of the todo item (required)
  description?: string; // Optional description for more details
  completed: boolean; // Whether the todo has been completed
  createdAt?: Date; // Automatically generated by Mongoose when document is created
  updatedAt?: Date; // Automatically updated by Mongoose when document is modified
}

/**
 * API Response interfaces for different endpoints
 * These help us maintain consistent API response formats
 */

// Response for fetching multiple todos
export interface TodosResponse {
  success: boolean; // Indicates if the operation was successful
  data: ITodo[]; // Array of todo items
  message?: string; // Optional message (e.g., for additional information)
}

// Response for operations on a single todo
export interface TodoResponse {
  success: boolean; // Indicates if the operation was successful
  data: ITodo | null; // A single todo item or null if not found
  message?: string; // Optional message (e.g., for additional information)
}

// Response for error cases
export interface ErrorResponse {
  success: boolean; // Always false for errors
  message: string; // Error message
}
